'use client';  // pragma to mark the module as client code
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7cWStv6ocus
 */
// Import the useRouter hook from next/router
import Link from 'next/link'

 import { useEffect } from 'react';
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/pages/ui/card"
import { Input } from "@/pages/ui/input"
import { Button } from "@/pages/ui/button"
import { useGlobalState } from '../contexts/GlobalStateContext';
import { GlobalStateProvider } from '../contexts/GlobalStateContext';

export default function Formtwo() {

  // Inside your Vraagone component function


  const { state, dispatch } = useGlobalState();


  const handleNextButtonClick = () => {
    console.log('Start Function');
    // Perform any necessary validation or processing of the input
    const inputValue = parseFloat(document.getElementById('amount').value) || 0;

    // Dispatch an action to update the total crypto value in the global state
    // dispatch({
    //   type: 'UPDATE_TOTAL_CRYPTO_VALUE',
    //   payload: inputValue,
    // });
    console.log('Updated Global State:', state);
     // Import the router inside the component
   
    // Navigate to the next step or perform other actions if needed
  };

  useEffect(() => {
    console.log('Updated Global State:', state);
  }, [state]);
  

  return (

    (<div
      key="1"
      className="flex justify-center items-center min-h-screen bg-gray-100 px-2 sm:px-4 lg:px-6">
      <Card className="w-full max-w-lg mx-auto">
        <CardHeader className="text-center">
          <CardTitle>
            Vraag 2 : Wat is de totale vermogen van je beleggingen, aandelen en obligaties (leningen die worden uitgegeven door bedrijven of overheden) op 1 januari.
          </CardTitle>
        </CardHeader>
        <CardContent className="flex flex-col items-center">
          <Input
            className="text-center"
            id="amount"
            min="0"
            placeholder="Voer het bedrag in euros in"
            step="0.01"
            type="number" />
        </CardContent>
        <CardFooter className="flex justify-center">
        <Link href="/Result"><Button>Volgende2</Button>
        </Link>
        </CardFooter>
      </Card>
    </div>)

  );
 
}
